name: mindbridge_web
description: MindBridge Web Dashboard - Mental Health Tracker
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Layout
  flutter_web_plugins:
    sdk: flutter
  responsive_framework: ^1.1.1
  flutter_layout_grid: ^2.0.5
  
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  
  # Charts & Data Visualization
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39
  
  # UI Components
  material_design_icons_flutter: ^7.0.7296
  flutter_animate: ^4.2.0+1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  
  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  
  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing Dependencies
  bloc_test: ^10.0.0
  mocktail: ^1.0.0
  mockito: ^5.4.2
  fake_async: ^1.3.1
  test: ^1.24.7
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  
  # Widget Testing
  golden_toolkit: ^0.15.0
  alchemist: ^0.12.1
  
  # Network Testing
  http_mock_adapter: ^0.6.1
  
  # Coverage
  coverage: ^1.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/ 