apiVersion: v1
kind: Secret
metadata:
  name: mindbridge-secrets
  namespace: mindbridge
  labels:
    app: mindbridge
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_USER: cG9zdGdyZXM=  # postgres
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # password
  
  # JWT secrets (base64 encoded - CHANGE THESE IN PRODUCTION)
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
  JWT_ALGORITHM: SFMyNTY=  # HS256
  
  # OpenAI API key (base64 encoded - SET THIS IN PRODUCTION)
  OPENAI_API_KEY: ""
  
  # Database URL (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9taW5kYnJpZGdlX3Byb2Q=
  
  # Redis URL (base64 encoded)
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA== 